/* ============================================================
   FILM-TREND AI — visual styles catalogue
   Every style direction on the market, grouped. The value is the
   English descriptor injected into the generation prompts.
   ============================================================ */

const STYLE_GROUPS = [
  {
    group: "🎬 سينمائي / واقعي",
    styles: [
      ["Cinematic photorealism, shallow depth of field, filmic color grade", "سينمائي واقعي (Cinematic Photorealism)"],
      ["Hyperrealistic 8K photography, ultra-detailed skin texture", "واقعية مفرطة (Hyperrealism)"],
      ["Documentary realism, natural available light, handheld authenticity", "وثائقي (Documentary)"],
      ["Teal and orange blockbuster grade, high contrast, anamorphic lens flares", "بلوكباستر Teal & Orange"],
      ["Golden hour naturalism, warm backlight, soft atmospheric haze", "الساعة الذهبية (Golden Hour)"],
      ["Film noir, hard chiaroscuro lighting, venetian blind shadows, black and white", "فيلم نوار (Film Noir)"],
      ["Neo-noir, neon-soaked night city, wet asphalt reflections, moody", "نيو نوار (Neo-Noir)"],
      ["Classic black and white 1950s cinema, silver gelatin look", "أبيض وأسود كلاسيكي"],
      ["Vintage 35mm film stock, visible grain, faded Kodachrome colors, 1970s", "فيلم 35mm فينتاج"],
      ["VHS retro 1980s, scan lines, chromatic aberration, camcorder look", "VHS ريترو 80s"],
      ["Wes Anderson symmetry, pastel palette, centered flat composition", "ويس أندرسون (تناظر وباستيل)"],
      ["A24 indie film aesthetic, muted colors, intimate natural light", "فيلم إندي A24"],
      ["Epic IMAX scale, sweeping vistas, monumental composition", "ملحمي IMAX"],
      ["Horror atmosphere, desaturated cold palette, deep shadows, unsettling", "رعب (Horror)"],
    ],
  },
  {
    group: "🧸 أنيميشن 3D",
    styles: [
      ["Pixar-style 3D animation, expressive characters, soft global illumination", "بيكسار 3D"],
      ["DreamWorks 3D animation style, dynamic poses, vivid colors", "دريم وركس 3D"],
      ["Disney 3D animation, polished render, magical lighting", "ديزني 3D"],
      ["Claymation stop-motion, visible fingerprints, Aardman style", "صلصال Stop-Motion"],
      ["LEGO brick animation style, plastic sheen, modular world", "ليجو (LEGO)"],
      ["Low-poly 3D art, flat shaded geometric forms, minimalist", "لو بولي (Low-Poly)"],
      ["Unreal Engine 5 cinematic render, ray tracing, photoreal CGI", "رندر Unreal Engine"],
      ["Cute Funko-Pop style 3D figures, big heads, vinyl toy look", "فانكو بوب (شخصيات لعب)"],
    ],
  },
  {
    group: "🎌 أنيمي / 2D",
    styles: [
      ["Studio Ghibli anime, painterly backgrounds, soft watercolor skies", "أنيمي جيبلي (Ghibli)"],
      ["Modern shonen anime, dynamic action lines, cel shading, vibrant", "أنيمي شونين حديث"],
      ["Retro 90s anime, film grain, muted VHS colors, hand-drawn cels", "أنيمي 90s ريترو"],
      ["Manga black and white, screentone shading, ink lines", "مانجا أبيض وأسود"],
      ["American comic book style, bold ink outlines, halftone dots, dramatic", "كوميكس أمريكي"],
      ["Classic Disney 2D hand-drawn animation, fluid motion, warm", "ديزني 2D كلاسيكي"],
      ["Flat cartoon style, thick outlines, saturated simple shapes", "كرتون فلات (Cartoon Network)"],
      ["Webtoon style, clean digital lines, soft gradient coloring", "ويبتون (Webtoon)"],
    ],
  },
  {
    group: "🎨 فني / رسم",
    styles: [
      ["Watercolor painting, bleeding pigments, textured paper", "ألوان مائية (Watercolor)"],
      ["Classical oil painting, visible brushstrokes, Rembrandt lighting", "زيتي كلاسيكي (Oil Painting)"],
      ["Impressionist painting, loose dabs of color, Monet-like light", "انطباعي (Impressionist)"],
      ["Van Gogh style, swirling expressive brushwork, thick impasto", "فان جوخ"],
      ["Pop art, Warhol screenprint colors, bold graphic repetition", "بوب آرت (Pop Art)"],
      ["Japanese ukiyo-e woodblock print, flat perspective, Hokusai waves", "أوكييو-إه ياباني"],
      ["Art nouveau, ornate flowing linework, Mucha decorative frames", "آرت نوفو"],
      ["Pencil sketch, rough graphite lines, crosshatched shading", "سكتش رصاص"],
      ["Charcoal drawing, smudged dramatic blacks, expressive strokes", "فحم (Charcoal)"],
      ["Production storyboard sketch, loose grayscale marker, annotation arrows", "سكتش استوري بورد إنتاجي"],
      ["Children's book illustration, soft gouache, whimsical warmth", "رسوم كتب أطفال"],
      ["Vintage travel poster, flat colors, art deco typography", "بوستر سفر فينتاج"],
    ],
  },
  {
    group: "🚀 خيالي / رقمي",
    styles: [
      ["Cyberpunk, neon signs, rain-slicked megacity, holographic ads", "سايبر بانك (Cyberpunk)"],
      ["Synthwave retrofuturism, magenta-cyan gradient, sunset grid horizon", "سينث ويف (Synthwave)"],
      ["Vaporwave aesthetic, pastel pink and teal, greek statues, glitch", "فيبور ويف (Vaporwave)"],
      ["Steampunk, brass gears, victorian machinery, warm gaslight", "ستيم بانك (Steampunk)"],
      ["Solarpunk utopia, lush greenery on futuristic architecture, bright optimism", "سولار بانك (Solarpunk)"],
      ["Epic high fantasy, dramatic god rays, painterly concept art", "فانتازيا ملحمية"],
      ["Dark fantasy, gothic ruins, desaturated palette, ominous fog", "فانتازيا مظلمة"],
      ["Hard sci-fi futurism, clean white surfaces, minimal spacecraft interiors", "خيال علمي مستقبلي"],
      ["Space opera, nebula backdrops, colossal starships, cosmic scale", "أوبرا فضائية"],
      ["Post-apocalyptic wasteland, rusted decay, dusty haze", "ما بعد نهاية العالم"],
      ["Afrofuturism, ornate gold patterns, vibrant textiles, futuristic Africa", "أفروفيوتشرزم"],
      ["Dreamcore surrealism, impossible architecture, liminal spaces", "سيريالي حالم (Dreamcore)"],
    ],
  },
  {
    group: "📸 إعلاني / تجاري",
    styles: [
      ["Clean studio product photography, seamless background, softbox lighting", "تصوير منتجات استوديو"],
      ["Luxury fashion editorial, high-end magazine lighting, elegant minimalism", "فاشون إديتوريال فاخر"],
      ["Appetizing food photography, macro details, steam, backlit freshness", "تصوير أكل (Food)"],
      ["Authentic UGC iPhone footage look, natural imperfect framing, relatable", "UGC طبيعي (شكل موبايل)"],
      ["Flat lay top-down composition, organized objects, pastel background", "فلات لاي (Flat Lay)"],
      ["Minimalist Scandinavian aesthetic, white space, muted earth tones", "مينيمال اسكندنافي"],
      ["Bold streetwear campaign, urban grit, flash photography, attitude", "ستريت وير جريء"],
      ["Corporate clean tech aesthetic, blue gradient, glass and light", "تِك كوربوريت نظيف"],
      ["Real estate architectural photography, wide angle, bright airy interiors", "تصوير معماري وعقاري"],
      ["Sports energy commercial, frozen motion, sweat particles, dramatic rim light", "إعلان رياضي (Energy)"],
    ],
  },
  {
    group: "✨ مؤثرات خاصة",
    styles: [
      ["Double exposure, silhouette blended with landscape", "دبل إكسبوجر"],
      ["Glitch art, databending distortion, RGB channel split", "جليتش آرت (Glitch)"],
      ["Isometric 3D diorama, miniature world, clean geometry", "أيزومتريك ديوراما"],
      ["Pixel art 8-bit retro game style", "بيكسل آرت 8-bit"],
      ["Papercraft cutout layers, depth shadows, handmade feel", "بيبر كرافت (ورق)"],
      ["Origami folded paper world, crisp creases, minimal palette", "أوريجامي"],
      ["Neon glow outlines on black, electric luminescence", "نيون جلو"],
      ["Holographic iridescent chrome, y2k futurism", "هولوجرام Y2K"],
      ["Tilt-shift miniature effect, toy-like world, selective focus", "تيلت شيفت (عالم مصغر)"],
      ["X-ray transparent blueprint look, technical schematic lines", "بلوبرنت هندسي"],
      ["Macro photography, extreme close-up textures, shallow focus", "ماكرو (تفاصيل دقيقة)"],
      ["Infrared photography, surreal red foliage, dreamlike tones", "إنفراريد (أشعة تحت الحمراء)"],
    ],
  },
];
